application: second-bit
version: 1
runtime: python
api_version: 1

handlers:
- url: /admin/images/(add|edit).*
  script: handlers/images/add_edit.py
  login: admin
- url: /admin/images/resize/(.*)
  script: handlers/images/resize.py
- url: /image/(.*)
  script: handlers/images/view.py
- url: /admin/images
  script: handlers/images/list.py
- url: /admin/images/
  script: handlers/images/list.py
- url: /images
  static_dir: template/images
- url: /js
  static_dir: template/js
- url: /style
  static_dir: template/style
- url: /404
  static_files: template/404.html
  upload: template/404.html
- url: /admin
  script: admin/dashboard.py
- url: /admin/(add|edit).*
  script: admin/edit.py
- url: /portfolio
  script: portfolio.py
- url: /
  script: main.py
- url: .*
  script: page.py
