application: second-bit
version: 1
runtime: python
api_version: 1

handlers:
- url: /admin/images/(add|edit).*
  script: handlers/images/add_edit.py
  login: admin
- url: /admin/images/resize/(.*)
  script: handlers/images/resize.py
  login: admin
- url: /image/(.*)
  script: handlers/images/view.py
- url: /admin/images
  script: handlers/images/list.py
  login: admin
- url: /admin/images/
  script: handlers/images/list.py
  login: admin
- url: /admin/links/(add|edit).*
  script: handlers/links/add_edit.py
  login: admin
- url: /admin/links/delete/(.*)
  script: handlers/links/delete.py
  login: admin
- url: /admin/links
  script: handlers/links/list.py
  login: admin
- url: /admin/links/
  script: handlers/links/list.py
  login: admin
- url: /admin/pages/(add|edit).*
  script: handlers/pages/add_edit.py
  login: admin
- url: /images
  static_dir: template/images
- url: /js
  static_dir: template/js
- url: /style
  static_dir: template/style
- url: /404
  static_files: template/404.html
  upload: template/404.html
- url: /.*
  script: handlers/pages/view.py
