application: second-bit
version: 1
runtime: python
api_version: 1

skip_files: |
 ^(.*/)?(
 (app\.yaml)|
 (app\.yml)|
 (index\.yaml)|
 (index\.yml)|
 (#.*#)|
 (.*~)|
 (.*\.py[co])|
 )$
 
handlers:
- url: /admin/images/(add|edit).*
  script: handlers/images/add_edit.py
  login: admin
- url: /admin/images/resize/(.*)
  script: handlers/images/resize.py
  login: admin
- url: /image/(.*)
  script: handlers/images/view.py
- url: /admin/images
  script: handlers/images/list.py
  login: admin
- url: /admin/images/
  script: handlers/images/list.py
  login: admin
- url: /admin/links/(add|edit).*
  script: handlers/links/add_edit.py
  login: admin
- url: /admin/links/delete/(.*)
  script: handlers/links/delete.py
  login: admin
- url: /admin/links
  script: handlers/links/list.py
  login: admin
- url: /admin/links/
  script: handlers/links/list.py
  login: admin
- url: /admin/pages/(add|edit).*
  script: handlers/pages/add_edit.py
  login: admin
- url: /admin/pages/delete/.*
  script: handlers/pages/delete.py
  login: admin
- url: /admin/pages
  script: handlers/pages/list.py
  login: admin
- url: /admin/pages/
  script: handlers/pages/list.py
  login: admin
- url: /admin/projects/(add|edit).*
  script: handlers/projects/add_edit.py
  login: admin
- url: /admin/projects
  script: handlers/projects/list.py
  login: admin
- url: /admin/projects/
  script: handlers/projects/list.py
  login: admin
- url: /admin/services/(add|edit).*
  script: handlers/services/add_edit.py
  login: admin
- url: /admin/services
  script: handlers/services/list.py
  login: admin
- url: /admin/services/
  script: handlers/services/list.py
  login: admin
- url: /admin/people/(add|edit).*
  script: handlers/people/add_edit.py
  login: admin
- url: /projects/[^/]*/(image|thumb)/.*
  script: handlers/projects/images.py
- url: /projects/[^/]*/reviews
  script: handlers/reviews/view_project.py
- url: /projects/[^/]*/reviews/
  script: handlers/reviews/view_project.py
- url: /projects/[^/]*/reviews/.*
  script: /handlers/reviews/view.py
- url: /projects
  script: /handlers/projects/view_all.py
- url: /projects/
  script: /handlers/projects/view_all.py
- url: /projects/.*
  script: handlers/projects/view.py
- url: /services/[^/]*/icon
  script: handlers/services/images.py
- url: /team
  script: handlers/people/view_all.py
- url: /team/
  script: handlers/people/view_all.py
- url: /team/.*
  script: handlers/people/view.py
- url: /services
  script: handlers/services/view_all.py
- url: /services/
  script: handlers/services/view_all.py
- url: /services/.*
  script: handlers/services/view.py
- url: /admin/reviews
  script: handlers/reviews/list.py
  login: admin
- url: /admin/reviews/
  script: handlers/reviews/list.py
  login: admin
- url: /admin/reviews/(add|edit).*
  script: handlers/reviews/add_edit.py
  login: admin
- url: /images
  static_dir: template/hauk/images
- url: /favicon.ico
  static_files: /favicon.ico
  upload: template/hauk/images/favicon.ico
- url: /js
  static_dir: template/hauk/js
- url: /style
  static_dir: template/hauk/style
- url: /404
  static_files: template/404.html
  upload: template/404.html

- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin

- url: /_ah/queue/deferred
  script: bloggart/deferred.py
  login: admin

- url: /admin/blog/.*
  script: bloggart/admin.py
  login: admin

- url: /admin/blog
  script: bloggart/admin.py
  login: admin
  
- url: /static/([^/]+)/(.*)
  static_files: bloggart/themes/\1/static/\2
  upload: bloggart/themes/[^/]+/static/.*

- url: /blog/.*
  script: bloggart/static.py

- url: /blog
  script: bloggart/static.py


- url: /
  script: main.py
- url: /.*
  script: handlers/pages/view.py
